[workspace]
channels = ["conda-forge", "bioconda"]
name = "forge"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bwa = "*"
samtools = "*"
gatk4 = "*"
bcftools = "*"
snpeff = "*"
snpsift = "*"

jq = "*"

python = "*"

[pypi-dependencies]
argparse = "*"
pyyaml = "*"
pandas = "*"
seaborn = "*"
cyvcf2 = "*"

[environments]
forge = []
